// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvQTsa5eZuD7Gygi8e0GjkAif2a8FA6LE',
    appId: '1:316936023784:web:bd1208962823194e8ee35d',
    messagingSenderId: '316936023784',
    projectId: 'polymed-1abf1',
    authDomain: 'polymed-1abf1.firebaseapp.com',
    storageBucket: 'polymed-1abf1.appspot.com',
    measurementId: 'G-9QNVDR03VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0YJQYWqTZSQEYkLOK_gldDr5LJl-WWc',
    appId: '1:316936023784:android:14baba6bdaf1acc38ee35d',
    messagingSenderId: '316936023784',
    projectId: 'polymed-1abf1',
    storageBucket: 'polymed-1abf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhfe6RInMbBT2Pd8HwytSP0C_B4Dt89VY',
    appId: '1:316936023784:ios:e6c22aff6487791c8ee35d',
    messagingSenderId: '316936023784',
    projectId: 'polymed-1abf1',
    storageBucket: 'polymed-1abf1.appspot.com',
    iosBundleId: 'com.example.polymed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhfe6RInMbBT2Pd8HwytSP0C_B4Dt89VY',
    appId: '1:316936023784:ios:e6c22aff6487791c8ee35d',
    messagingSenderId: '316936023784',
    projectId: 'polymed-1abf1',
    storageBucket: 'polymed-1abf1.appspot.com',
    iosBundleId: 'com.example.polymed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvQTsa5eZuD7Gygi8e0GjkAif2a8FA6LE',
    appId: '1:316936023784:web:99a80f409006f5798ee35d',
    messagingSenderId: '316936023784',
    projectId: 'polymed-1abf1',
    authDomain: 'polymed-1abf1.firebaseapp.com',
    storageBucket: 'polymed-1abf1.appspot.com',
    measurementId: 'G-ZLLFVFTY1E',
  );
}
